# Generated by Django 2.2.5 on 2022-08-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatManage', '0002_seat_img_seat_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='flag',
            field=models.IntegerField(default=0, verbose_name='过期标志'),
        ),
    ]
