# Generated by Django 3.2.14 on 2022-08-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatManage', '0003_userinfo_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='flag',
            field=models.IntegerField(default=1, verbose_name='过期标志'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_phone',
            field=models.CharField(max_length=30, verbose_name='电话'),
        ),
    ]
