# Generated by Django 3.2.14 on 2022-08-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatManage', '0005_auto_20220803_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='active_day',
            field=models.IntegerField(default=0, verbose_name='活跃天数'),
        ),
    ]
