# Generated by Django 3.2.14 on 2022-08-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatManage', '0006_alter_userinfo_active_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_card_number',
            field=models.CharField(default=0, max_length=15, verbose_name='卡号'),
        ),
    ]
