# Generated by Django 3.2.14 on 2022-08-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatManage', '0008_auto_20220807_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='card_create_time',
            field=models.BigIntegerField(verbose_name='开卡日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='card_expiration_time',
            field=models.BigIntegerField(verbose_name='卡过期日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='info_change_time',
            field=models.BigIntegerField(verbose_name='更改信息时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='modified_time',
            field=models.BigIntegerField(verbose_name='修改操作时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='stop_time',
            field=models.BigIntegerField(verbose_name='暂停时间'),
        ),
    ]
