# Generated by Django 3.2.14 on 2022-08-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatManage', '0009_auto_20220807_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
